DECLARE @V1 VARCHAR(MAX)
DECLARE @V2 VARCHAR(MAX)
DECLARE @V3 VARCHAR(MAX)
DECLARE @V4 VARCHAR(MAX)
SET @V1 = (SELECT MIN(LEN(CITY)) FROM STATION);
SET @V2 = (SELECT TOP 1 CITY FROM STATION WHERE LEN(CITY) = @V1 ORDER BY CITY );
SET @V3 = (SELECT MAX(LEN(CITY)) FROM STATION);
SET @V4 = (SELECT TOP 1 CITY FROM STATION WHERE LEN(CITY) = @V3 ORDER BY CITY );
SELECT @V2,@V1; SELECT @V4,@V3;